version: '3.8'

services:
  # Next.js Application
  tiennghe-app:
    build: .
    # Chỉ expose internal port, không expose ra host
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_VERCEL_ENV=production
      - REACT_EDITOR=atom
    restart: unless-stopped
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS (for future SSL)
    volumes:
      # Use HTTP config first, will switch to SSL later
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

      # Webroot for Let's Encrypt challenges
      - ./certbot/www:/var/www/certbot:ro

      # SSL certificates (will be created later)
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - tiennghe-app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
